config/routes.rb
Example::Application.routes.draw do
  resources :schedules

     resources :people

   root :to => 'people#index'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  attr_accessible :DayMorning, :DayAfternoon, :EndMorning, :EndAfternoon

  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  
  attr_accessible :address, :email, :first, :last, :userNumber, :location, 
		  :phone, :position, 
		  :dayMorning, :dayAfternoon, :endMorning, :endAfternoon

  has_one :schedule
  has_one :availability
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :name, :lifeguard, :manager
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, :notice => 'Person was successfully created.' }
        format.json { render :json => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.json { render :json => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, :notice => 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, :notice => 'Schedule was successfully created.' }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, :notice => 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    User ID
    <%#= f.label :userNumber %><br />
    <%= f.text_field :userNumber %>
  </div>

  <div class="field>
    <b> Availability </b>
  </div>

  <div class="field">
    Weekday Mornings
    <%#= f.label :dayMorning %><br />
    <%= f.check_box :dayMorning %>
  </div>
<br>
  <div class="field">
    Weekday Afternoons
    <%#= f.label :dayAfternoon %><br />
    <%= f.check_box :dayAfternoon %>
  </div>
<br>
  <div class="field">
    Weekend Mornings
    <%#= f.label :endMorning %><br />
    <%= f.check_box :endMorning %>
  </div>
<br>
  <div class="field">
    Weekend Afternoons
    <%#= f.label :endAfternoon %><br />
    <%= f.check_box :endAfternoon %>
  </div>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table class="table table-striped">
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Address</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Location</th>
    <th>Position</th>
    <th>User ID</th>
    <th>Availability</th>
    <th>Weekday Mornings</th>
    <th>Weekday Afternoons</th>
    <th>Weekend Mornings</th>
    <th>Weekend Afternoons</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first %></td>
    <td><%= person.last %></td>
    <td><%= person.address %></td>
    <td><%= person.email %></td>
    <td><%= person.phone %></td>
    <td><%= person.location %></td>
    <td><%= person.position %></td>
    <td><%= person.userNumber %></td>
    <td> </td>
    <td><% if person.dayMorning == "true" %>
	  Available 
        <% else %>
	  Unavailable  
        <% end %>
    </td>
    <td> <%= person.dayAfternoon %>
<%# if person.dayAfternoon == "true %>
        <%# else %>
        <%# end %>
    </td>
    <td><%= person.endMorning %>
<%# if person.endMorning == "true" %>
        <%# else %>
        <%# end %>
    </td>
    <td><%= person.endAfternoon %>
<%# if person.endAfternoon == "true" %>
        <%# else %>
        <%# end %>
    </td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>


<%= link_to 'Schedules', new_schedule_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First:</b>
  <%= @person.first %>
</p>

<p>
  <b>Last:</b>
  <%= @person.last %>
</p>

<p>
  <b>Address:</b>
  <%= @person.address %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @person.phone %>
</p>

<p>
  <b>Location:</b>
  <%= @person.location %>
</p>

<p>
  <b>Position:</b>
  <%= @person.position %>
</p>

<p>
  <b>User ID:</b>
  <%= @person.userNumber %>
</p>

<p>
  <b>Availability:</b>
</p>

<p>
  <b>Weekday Mornings:</b>
  <%= @person.dayMorning %>
</p>

<p>
  <b>Weekday Afternoons:</b>
  <%= @person.dayAfternoon %>
</p>

<p>
  <b>Weekend Mornings:</b>
  <%= @person.endMorning %>
</p>

<p>
  <b>Weekday Afternoons:</b>
  <%= @person.endAfternoon %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class ="field">
    <%= f.label :lifeguard %>
    <%= f.select("lifeguard", Person.find(:all)) %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.name %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @schedule.name %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>